emit:
  - "@typespec/openapi3"
  - "@microsoft/typespec-copilot-skills"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{project-root}/.generated/openapi"
    output-file: examplesapi.json
    file-type: json 
  "@microsoft/typespec-copilot-skills":
    emitter-output-dir: "{project-root}/.generated/openapi"
    output-file: declarativeAgent.json  # Doesn't work but makes the emitter work :-)
    file-type: json 